version: '3'

services:
   nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    command: /bin/bash -c "nginx -g 'daemon off;'"
    volumes:
      - ./_site:/usr/share/nginx/html
      - ./conf/nginx.conf.local:/etc/nginx/nginx.conf:ro
